### ISSUE TITLE
How to work with [String] and [String]?

### ISSUE THREAD

**Issue by davidarice** [davidsteppenbeck/ObservableUserDefault#2]
Is there a trick to getting this to work with an array? At the moment I simply using the following method: 

`    var favorites: [String] {
        get {
            access(keyPath: \.favorites)
            return UserDefaults.standard.value(forKey: "favorites") as? [String] ?? []
        }
        set {
            withMutation(keyPath: \.favorites) {
                UserDefaults.standard.set(newValue, forKey: "favorites")
            }
        }
    }`

**Comment by davidsteppenbeck** [comment]
Thanks for pointing that out. Fixed it, should now work with arrays and dictionaries.

**Comment by davidsteppenbeck** [comment]
Thanks for pointing that out. Fixed it, should now work with arrays and dictionaries.
